dump_dir: dump/debug3
steps: 200_000
probe_freq: 100
seed: 777

optim:
  lr: 3e-4
  weight_decay: 0.033
  warmup: 5000
  lr_min_ratio: 0.000001
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  dp_shard: 3
  tp_size: 1

model:
  dim: 1024
  n_layers: 16
  n_heads: 16
  max_seqlen: 2048

data:
  root_dir: data
  sources:
      fineweb_edu_10bt_shuffled: 100.0
  batch_size: 16
  prefetch_size: 32
  seq_len: 2048
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    path: tokenizer/llama3/original/tokenizer.model

profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 2500
    keep: 3
  eval:
    every: 5000
    keep: 1

logging:
    freq: 10
    wandb:
        project: "utllm-lingua"

eval:
  harness:
    tasks:
      - hellaswag
      - piqa
      - mmlu
  generator:
    max_tokens: 4096
    dtype: bf16
