debugname: dump/debug2
steps: 60_000
probe_freq: 100
seed: 777

optim:
  lr: 3e-4
  weight_decay: 0.033
  warmup: 5000
  lr_min_ratio: 0.000001
  clip: 1.0

distributed:
  fsdp_type: shard_grad_op
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 1024
  n_layers: 8
  n_heads: 8

data:
  root_dir: data
  sources:
      fineweb_edu_10bt_shuffled: 100.0
  batch_size: 32
  prefetch_size: 64
  seq_len: 4096
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    path: tokenizer/llama3/original/tokenizer.model

profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 2500
    keep: 3
  eval:
    every: 5000
    keep: 1

logging:
    freq: 10
    wandb:
        project: "utllm-lingua"

async_eval_gpus: 2
eval:
  harness:
    tasks:
      - hellaswag
      - nq_open
      - piqa
      - siqa
      - csatqa
      - winogrande
      - arc
      - race
      - gsm8k
      - bbh
      - mmlu
  generator:
    max_tokens: 16384
    dtype: bf16
